pub mod app;
pub mod color;
pub mod commands;
pub mod custom_terminal;
pub mod events;
pub mod footer;
pub mod history_render;
pub mod insert_history;
pub mod key_hint;
pub mod palette;
pub mod shimmer;
pub mod status_indicator;
pub mod style;
pub mod terminal_palette;
#[cfg(test)]
pub mod test_backend;
pub mod transcript_store;
pub mod ui;
pub mod wrapping;
